### ISSUE TITLE
New profiles are created with superuser and staff access

### ISSUE THREAD

**Issue by newgrounds** [HumanDynamics/openPDS-RegistryServer#8]
The check boxes don't change this status.

Currently the only way to remove the access is to log into Django Admin and deselect the boxes in each user's page under Auth -> Users.

**Comment by brian717** [comment]
Fixed with 2913893c6ed7b4e23a3678c6b6f3af42f94221fd

**Comment by newgrounds** [comment]
Just confirming that this has been fixed.
